/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class med_voll_api_testes_memoria_TestaPC */

#ifndef _Included_med_voll_api_testes_memoria_TestaPC
#define _Included_med_voll_api_testes_memoria_TestaPC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     med_voll_api_testes_memoria_TestaPC
 * Method:    soma
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_med_voll_api_testes_memoria_TestaPC_soma
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
